name: Bug Report
description: Report a bug in mulch-cli
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What did you do?
      placeholder: |
        1. Run `mulch record ...`
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: mulch-version
    attributes:
      label: mulch version
      description: Output of `mulch --version`
      placeholder: "0.5.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node version
      description: Output of `node --version`
      placeholder: "v18.0.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 15, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: true
